### ISSUE TITLE
Walidacja wygenerowanego pliku xml w stosunku do schematu xsd

### ISSUE THREAD

**Issue by Apokrbk** [chodi150/projektPIK#16]
Po podmianie wartości w szablonie dostarczonym przez testera należy sprawdzić czy wygenerowany plik xml jest zgodny ze schematem xsd danego szablonu. Do sprawdzenia czy plik xml posiada odpowiednią strukturę i odpowiednie znaczniki, czy znaczniki oznaczone jako obligatoryjne są wypełnione, czy zgadzają się typy danych.

**Comment by chodi150** [comment]
Proszę o weryfikację:
6454cdb7414f73a6c1e52c4310ea1747da7beb81
