### ISSUE TITLE
Walidacja wygenerowanego pliku xml z plikiem utworzonym przez testera

### ISSUE THREAD

**Issue by Apokrbk** [chodi150/projektPIK#17]
W celu dodatkowej weryfikacji poprawności wygenerowanego pliku xml tester przygotowuje ręcznie wypełniony plik z podmienionymi wartościami a następnie wygenerowany plik jest porównywany linijka po linijce z plikiem wypełnionym przez testera.

**Comment by chodi150** [comment]
Proszę o weryfikację:
6454cdb7414f73a6c1e52c4310ea1747da7beb81
