### ISSUE TITLE
ReadMe i travis status

### ISSUE THREAD

**Issue by kkoziol** [chodi150/projektPIK#26]
Jako "sprawdzajacy" ....
chciałbuym miec ładne ReadMe z pieknym zielonym statusem buildów Travisa.

**Comment by chodi150** [comment]
Readme ze statusem buildow travisa dostępne w module WebApp, ponieważ moduł ten jest modułem startowym naszej aplikacji, który korzysta z frameworkow testowego XmlTestingTool jako dependencji.

**Comment by kkoziol** [comment]
dzieki, tak juz sie wlasnie dokopałem. do niego.
